CREATE TABLE `task_module` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `ID_ORDER` INT(11) NOT NULL,
        `DESCRIPTION` TEXT NOT NULL,
        `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(ID) );